package `in`.surajsau.jisho.ui.theme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val LightColors = lightColorScheme(
    primary = Color(0xFFBF002E),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDAD9),
    onPrimaryContainer = Color(0xFF400009),
    secondary = Color(0xFF9B4050),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFD9DC),
    onSecondaryContainer = Color(0xFF400011),
    tertiary = Color(0xFF835400),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDDB5),
    onTertiaryContainer = Color(0xFF2A1800),
    error = Color(0xFFBA1A1A),
    errorContainer = Color(0xFFFFDAD6),
    onError = Color(0xFFFFFFFF),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFFBFF),
    onBackground = Color(0xFF201A1A),
    surface = Color(0xFFFFFBFF),
    onSurface = Color(0xFF201A1A),
    surfaceVariant = Color(0xFFF4DDDC),
    onSurfaceVariant = Color(0xFF524343),
    outline = Color(0xFF857372),
    inverseOnSurface = Color(0xFFFBEEED),
    inverseSurface = Color(0xFF362F2E),
    inversePrimary = Color(0xFFFFB3B3),
    surfaceTint = Color(0xFFBF002E),
    outlineVariant = Color(0xFFD7C1C1),
    scrim = Color(0xFF000000),
)

internal val DarkColors = darkColorScheme(
    primary = Color(0xFFFFB3B3),
    onPrimary = Color(0xFF680014),
    primaryContainer = Color(0xFF920021),
    onPrimaryContainer = Color(0xFFFFDAD9),
    secondary = Color(0xFFFFB2BB),
    onSecondary = Color(0xFF5F1224),
    secondaryContainer = Color(0xFF7D2939),
    onSecondaryContainer = Color(0xFFFFD9DC),
    tertiary = Color(0xFFFFB957),
    onTertiary = Color(0xFF462B00),
    tertiaryContainer = Color(0xFF643F00),
    onTertiaryContainer = Color(0xFFFFDDB5),
    error = Color(0xFFFFB4AB),
    errorContainer = Color(0xFF93000A),
    onError = Color(0xFF690005),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF201A1A),
    onBackground = Color(0xFFECE0DF),
    surface = Color(0xFF201A1A),
    onSurface = Color(0xFFECE0DF),
    surfaceVariant = Color(0xFF524343),
    onSurfaceVariant = Color(0xFFD7C1C1),
    outline = Color(0xFFA08C8C),
    inverseOnSurface = Color(0xFF201A1A),
    inverseSurface = Color(0xFFECE0DF),
    inversePrimary = Color(0xFFBF002E),
    surfaceTint = Color(0xFFFFB3B3),
    outlineVariant = Color(0xFF524343),
    scrim = Color(0xFF000000),
)
